Repository SeniorSA/tecnologia-webcomponents, pull requests merged in 2021-04, with the labels that each got.

#39 fix modal close icon position
  CHANGELOG.md
  src/components.d.ts
  src/components/tec-modal/tec-modal.scss
  src/components/tec-modal/tec-modal.tsx
  src/components/tec-modal/test/tec-modal.spec.tsx
Labels: bug

#40 Generate 0.5.1
  CHANGELOG.md
  package.json
  src/components.d.ts
  src/components/tec-modal/tec-modal.scss
  src/components/tec-modal/tec-modal.tsx
  src/components/tec-modal/test/tec-modal.spec.tsx
Labels: release

#36 Add input code to fill token
  .eslintrc.json
  .gitignore
  .vscode/launch.json
  CHANGELOG.md
  CONTRIBUTING.md
  package-lock.json
  package.json
  screenshot/.gitignore
  src/components.d.ts
  src/components/button/button.model.ts
  src/components/button/button.scss
  src/components/button/button.stories.tsx
  src/components/button/button.tsx
  src/components/button/readme.md
  src/components/button/test/button.e2e.ts
  src/components/button/test/button.spec.tsx
  src/components/inputs/code-input/code-input.model.ts
  src/components/inputs/code-input/code-input.scss
  src/components/inputs/code-input/code-input.tsx
  src/components/inputs/code-input/readme.md
  src/components/inputs/code-input/test/code-input.e2e.ts
  src/components/inputs/code-input/test/code-input.spec.tsx
  src/components/tec-button/tec-button.stories.tsx
  src/index.html
  src/models/case.model.ts
  src/utils/utils.spec.ts
  src/utils/utils.ts
  stencil.config.ts
Labels: components

#51 Remove property `block` from `bottom-bar` to not force scroll on the page.
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/bottom-bar/bottom-bar.scss
  src/components/inputs/code-input/readme.md
Labels: bug

#52 Add responsive property to code-input component
  CHANGELOG.md
  src/components.d.ts
  src/components/inputs/code-input/code-input.scss
  src/components/inputs/code-input/code-input.tsx
  src/components/inputs/code-input/readme.md
  src/components/inputs/code-input/test/code-input.spec.tsx
Labels: enhancement

#54 Fixed code input when is mobile.
  CHANGELOG.md
  src/components/inputs/code-input/code-input.scss
  src/components/inputs/code-input/code-input.tsx
  src/components/inputs/code-input/test/code-input.spec.tsx
Labels: bug
